languageCode: 'da-DK'
baseURL: 'https://aporia-fagblad.dk/'
title: 'Aporia'
theme: 'PaperMod'

pagination:
  pagerSize: 20

# For at kunne tilføje HTML billeder direkte, brugt på forsiden:)
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  ShowReadingTime: false
  ShowBreadCrumbs: false
  assets.theme_color: "#ffe4e1"
  disableAnchoredHeadings: false
  disableHugoGenerator: true
  fonts:
    body: "Crimson Pro"
    heading: "Playfair Display"
  profileMode:
    enabled: true
    title: "Aporia - Det studenterdrevne Fagblad for Filosofi på Aarhus universitet" # optional default will be site title
    imageUrl: "images/aporia.jpg" # optional
    imageTitle: "Aporia logo" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size
    defualtTheme: auto # Automatically shift theme depending on system
    buttons:
      -  name: Udgivelser
         url: "https://exukia.github.io/aporia-fagblad/udgivelser/"
      -  name: Kontakt
         url: "https://exukia.github.io/aporia-fagblad/kontakt/"
      -  name: ⭐ Seneste ⭐
         url: "https://exukia.github.io/aporia-fagblad/udgivelser/f2026/"

  socialIcons: # optional
    - name: "Facebook"
      url: "https://www.facebook.com/people/Aporia-filosofisk-studenterfagblad-p%C3%A5-AU/61575727716359/"

  favicon:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"

  customCSS:
    - "css/common/custom.css"
    - "css/common/footnotes.css"
    - "css/common/bibliography.css"
