main:
  - name: "Udgivelser"
    url: "/udgivelser/"
    weight: 10

  - name: "Forfatterguide"
    url: "/forfatterguide/"
    weight: 20

  - name: "Kontakt"
    url: "/kontakt/"
    weight: 30

  - name: "Om Aporia"
    url: "/om-Aporia/"
    weight: 40
